image: registry.gitlab.com/grupo-esfera/capacitacion/recursos/repartir

stages:
  - install
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - src/main/frontend/packages/assembly-runner/node_modules/

install:
  stage: install
  script:
    - echo "Limpiando cache de npm"
    - npm cache clean --force
    - echo "Instalando dependencias en assembly-runner"
    - npm ci --prefix src/main/frontend/packages/assembly-runner
  artifacts:
    paths:
      - src/main/frontend/packages/assembly-runner/node_modules/
    expire_in: 1 week

test-assembly:
  stage: test
  script:
    - echo "Ejecutando pruebas assembly"
    - cd src/main/frontend/packages/assembly-runner
    - npm test
  artifacts:
    when: always
    paths:
      - build/test-results/
